"""
Module de génération de fichiers SFV (Simple File Verification) pour releases Scene.
"""

import logging
import zlib
from pathlib import Path
from typing import List, Optional

logger = logging.getLogger(__name__)


def generate_sfv(
    release_name: str,
    release_dir: str | Path,
    files_to_verify: Optional[List[Path]] = None,
) -> Path:
    """
    Génère fichier SFV pour release Scene.

    Format : Simple File Verification avec CRC32.
    Format ligne : <filename> <crc32>

    Args:
        release_name: Nom release complet
        release_dir: Dossier release contenant fichiers
        files_to_verify: Liste fichiers à vérifier (si None, scanne release_dir)

    Returns:
        Chemin fichier SFV créé

    Raises:
        IOError: Si erreur création SFV
    """
    release_dir = Path(release_dir)
    release_dir.mkdir(parents=True, exist_ok=True)

    # Nom fichier SFV : release.name.lower().sfv
    sfv_filename = f"{release_name.lower()}.sfv"
    sfv_path = release_dir / sfv_filename

    # Si fichiers non spécifiés, scanner release_dir
    if files_to_verify is None:
        # Exclure SFV lui-même et dossier Sample
        files_to_verify = [
            f
            for f in release_dir.iterdir()
            if f.is_file() and f.suffix.lower() != ".sfv" and f.name != sfv_filename
        ]
    else:
        files_to_verify = [Path(f) for f in files_to_verify]

    # Trier fichiers par nom alphabétique
    files_to_verify.sort(key=lambda p: p.name.lower())

    # Calculer CRC32 et générer lignes SFV
    sfv_lines = []
    sfv_lines.append(f"; Generated by Scene Ebook Packer")
    sfv_lines.append(f"; Release: {release_name}")
    sfv_lines.append("")

    for file_path in files_to_verify:
        if not file_path.exists():
            logger.warning(f"Fichier introuvable pour SFV: {file_path}")
            continue

        try:
            crc32 = _calculate_crc32(file_path)

            # Nom fichier relatif à release_dir
            rel_path = file_path.relative_to(release_dir)
            sfv_lines.append(f"{rel_path} {crc32:08X}")

        except Exception as e:
            logger.error(f"Erreur calcul CRC32 pour {file_path}: {e}")
            continue

    # Écrire fichier SFV
    sfv_content = "\n".join(sfv_lines) + "\n"

    try:
        with open(sfv_path, "w", encoding="utf-8") as f:
            f.write(sfv_content)
        logger.info(f"Fichier SFV créé: {sfv_path}")
    except Exception as e:
        logger.error(f"Erreur écriture SFV: {sfv_path}: {e}")
        raise IOError(f"Impossible créer SFV: {e}")

    return sfv_path


def _calculate_crc32(filepath: Path) -> int:
    """
    Calcule CRC32 d'un fichier.

    Args:
        filepath: Chemin fichier

    Returns:
        CRC32 (entier)
    """
    crc_value = 0

    with open(filepath, "rb") as f:
        while chunk := f.read(8192):
            crc_value = zlib.crc32(chunk, crc_value)

    return crc_value & 0xFFFFFFFF
